name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Vercel Production Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Vercel CLI
        run: npm install -g vercel@latest

      - name: Deploy to Production
        run: vercel --prod --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: team_jV6IsjaYKbV7X1yEDqdhy4uT
          VERCEL_PROJECT_ID: prj_4NgyzaKG0JJ7nYk83jvxKfZXffAy
